services:
  phpserver:
    image: php:8.3.4-cli
    volumes:
      - ./phpserver:/usr/src/myapp
    working_dir: /usr/src/myapp
    ports:
      - 8000:8000
    restart: unless-stopped
    command: php -S 0.0.0.0:8000 init.php

  nodeserver:
    image: node:20
    volumes:
      - ./nodeserver:/usr/src/myapp
    working_dir: /usr/src/myapp
    ports:
      - 3000:3000
    restart: unless-stopped
    command: node server.js

  proxy:
    build: ./nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./www-data:/data/www
